services:
  # Servicio 1: La API que recibe las c√©dulas
  - type: web
    name: api-principal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: REDIS_URL
        fromService:
          name: cache-datos
          type: redis
          property: connectionString
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"

  # Servicio 2: El Bot que navega (Como Web Service para que sea gratis)
  - type: web
    name: bot-navegador
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/worker.js
    envVars:
      - key: REDIS_URL
        fromService:
          name: cache-datos
          type: redis
          property: connectionString
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"

  # Servicio 3: La base de datos Redis
  - type: redis
    name: cache-datos
    plan: free
    ipAllowList: []
