services:
  # 1. El cerebro: API que recibe las peticiones
  - type: web
    name: api-principal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: REDIS_URL
        fromService:
          name: cache-datos
          type: redis
          property: connectionString

  # 2. El m√∫sculo: El bot que navega (Worker)
  - type: worker
    name: bot-navegador
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/worker.js
    envVars:
      - key: REDIS_URL
        fromService:
          name: cache-datos
          type: redis
          property: connectionString

  # 3. La memoria: Redis (Ahora se define como servicio)
  - type: redis
    name: cache-datos
    plan: free
    ipAllowList: [] # Permite que tus otros servicios se conecten internamente
